# Generated by Django 3.1.6 on 2021-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='have_visa',
        ),
        migrations.AddField(
            model_name='requirement',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
