# Generated by Django 3.1.6 on 2021-03-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0006_booking_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_reservation',
            field=models.DateField(default='2021-03-17'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
