# Generated by Django 3.1.7 on 2021-03-18 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0007_auto_20210317_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_reservation',
            field=models.DateField(default='2021-03-18'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
