# Generated by Django 3.1.7 on 2021-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_auto_20210318_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
