# Generated by Django 3.1.7 on 2021-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_flight_destination_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_reservation',
            field=models.DateField(default='2021-04-07'),
        ),
    ]
